services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecommerce_admin
      POSTGRES_PASSWORD: gravity_pass
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database:/db
      - ./backend/database/docker-init.sh:/docker-entrypoint-initdb.d/00-init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_admin -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ecommerce_db
      DB_USER: ecommerce_admin
      DB_PASSWORD: gravity_pass
      DB_URL: postgresql://ecommerce_admin:gravity_pass@db:5432/ecommerce_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
